name: Build omnisette-server

on:
  push:

jobs:
  build:
    name: Build omnisette-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install additional rust targets
        run: rustup target add i686-unknown-linux-musl #x86_64-unknown-linux-musl

      - name: Cache rust
        uses: Swatinem/rust-cache@v2

      - name: Install cross
        run: cargo install cross

#      - name: Build for x86_64
#        run: cross build --release --target x86_64-unknown-linux-musl

      - name: Build for i686
        run: cross build --release --target i686-unknown-linux-musl

      - name: Move and rename binaries
        run: cp target/i686-unknown-linux-musl/release/omnisette-server target/omnisette-server-linux-i686-musl
#          cp target/x86_64-unknown-linux-musl/release/omnisette-server target/omnisette-server-linux-x86_64-musl

      - name: Upload to nightly release
        uses: IsaacShelton/update-existing-release@v1.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: "Build"
          tag: "build"
          files: target/omnisette-server-linux-i686-musl
