name: Build omnisette-server

on:
  push:

jobs:
  build:
    name: Build omnisette-server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Install additional rust targets
        run: rustup target add aarch64-unknown-linux-musl x86_64-unknown-linux-musl

      - name: Cache rust
        uses: Swatinem/rust-cache@v2

      - name: Install cross
        run: cargo install cross

      - name: Build for x86_64
        run: cross build --release --target x86_64-unknown-linux-musl

      - name: Build for aarch64
        run: cross build --release --target aarch64-unknown-linux-musl

      - name: Move and rename binaries
        run: |
          cp target/x86_64-unknown-linux-musl/release/omnisette-server target/omnisette-server-linux-x86_64-musl
          cp target/aarch64-unknown-linux-musl/release/omnisette-server target/omnisette-server-linux-aarch64-musl

      - name: Upload to new release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: build
          tag_name: build-${{ github.run_number }}
          files: |
            target/omnisette-server-linux-x86_64-musl
            target/omnisette-server-linux-aarch64-musl
          body: experimental
